#!/usr/bin/env php
<?php

try {
    /*--------------------------------------------------------------*/
    /* Make Application                                             */
    /*--------------------------------------------------------------*/

    /** @var \Luxury\Foundation\Bootstrap $bootstrap */
    $bootstrap = require_once __DIR__ . '/bootstrap/app.php';

    /** @var \App\Cli\Kernel $kernel */
    $kernel = $bootstrap->make(App\Cli\Kernel::class);

    /**
     * Parse the arguments pass to the cli
     */
    $kernel->setArgument($argv);

    /**
     * Handle the request
     */
    $kernel->handle();

} catch (\Exception $e) {
    echo $e->getMessage() . '<br>';
    echo '<pre>' . $e->getTraceAsString() . '</pre>';
    exit(255);
}
