#!/usr/bin/env php
<?php

/*--------------------------------------------------------------*/
/* Make Application                                             */
/*--------------------------------------------------------------*/

/** @var \Neutrino\Foundation\Bootstrap $bootstrap */
$bootstrap = require_once __DIR__ . '/bootstrap/app.php';

/** @var \App\Kernels\Cli\Kernel $kernel */
$kernel = $bootstrap->make(App\Kernels\Cli\Kernel::class);

/**
 * Parse the arguments pass to the cli
 */
$kernel->setArgument($argv);

/**
 * Run kernel
 */
$bootstrap->run($kernel);
